### ISSUE TITLE
MITM Request Sniffer doesn't work

### ISSUE THREAD

**Issue by mangoplane** [delebash/unreal_vault_organizer#3]
Hi,

I can't sniff the token with your tool. Essentially it freezes all network requests while its open on Windows 11. Do you happen to know how I can overcome that?

Kind regards.

**Comment by delebash** [comment]
Maybe you can just make an exception for the sniffer that way you don't have to have it disabled. or just disable it whenever you want to update the organizer.  Also Epic is coming out with a new marketplace system later this year heedfully it will have better organization features.  https://www.fab.com/
