### ISSUE TITLE
x

### ISSUE THREAD

**Issue by alyx4000** [delebash/unreal_vault_organizer#4]
x

**Comment by delebash** [comment]
I think so once you have  that token I think you can use any service but I am not sure.  Also there is a new progrtam that does better auth that you can checkout https://github.com/phoenixlzx/mochimochi you need node js and some setup.

**Comment by alyx4000** [comment]
haven't gone trough completely but that looks like it's your average device/refresh token authentication pretty much every modern FN/Epic/UnReal related lib/client has. I've been quoting off this topic and wanted to achieve same results. That's also where I found your YouTube with your Github and Repos.
https://github.com/claabs/epicgames-freegames-node/issues/91
