### ISSUE TITLE
[Title Sorting] Vault's is case sensitive, Epic's Launcher isn't

### ISSUE THREAD

**Issue by derossm** [delebash/unreal_vault_organizer#5]
If you want to have more consistency with the Epic version where features overlap, such as sorting by title, non-alpha characters like [] should appear first, followed by numbers, then remaining titles starting with alpha characters should all be case insensitive. I think that is the default behavior in-general for case-insensitive lexicographical sorting, but I included those details just in case.

I think this should be the default, so it is easy to compare results on the vault to the epic version at a glance, but maybe an option to refine how the sorting works could keep the current case-sensitive method available too.

More granularity is the point of your much appreciated app, after all, so no reason not to make this an option too in case it actually is something someone prefers. For my use case, the only thing I care about is version compatibility, but you never know.

**Comment by delebash** [comment]
Check the new release that works with FAB.  Also, there is new authentication method that does not require the sniffer component.  https://github.com/delebash/unreal_vault_organizer_tauri/releases/tag/uvo-v1.0.0
