### ISSUE TITLE
Visual bug

### ISSUE THREAD

**Issue by derossm** [delebash/unreal_vault_organizer#6]
Scrolling off screen from newly added tags causes them to disappear visually when scrolling back, but refreshing the grid makes them visible again and persistent so this is only a visual bug. It is a bug only for recently added tags that weren't added before the last "refresh grid" or similar action has taken place, and such actions seem to be required to make added tags persistently visible.

It is kind of complicated how it works, and my description isn't exactly accurate. The most recently added tag isn't cleared, only all other tags not copies of the the same tag. I.E. adding "blueprint" to 5 entries, then adding "code" to a 6th, scroll up and down, then the 5 "blueprint" tags are missing but the code will show, then add a "vfx" tag to something, scroll up and down, and the code tag will be gone. But, it doesn't always affect the currently highlight entry. And sometimes not the entries next to it.

The reverse happens when tags are removed; i.e. scroll away and they will show up again until refreshed.

I don't have time right now to test more precisely the conditions that cause the bug and what conditions don't cause it. I might come back to this if I remember.

**Comment by delebash** [comment]
Thanks for reporting this bug.  Right now I will not be working on this application as Unreal will be moving everything over to the new marketplace FAB later this year.  Hopefully FAB will have all the features we need.  If not I will have to re-write the application as the api calls will be different and I will look at this bug then.

**Comment by delebash** [comment]
Check the new release that works with FAB.  Also, there is new authentication method that does not require the sniffer component.  https://github.com/delebash/unreal_vault_organizer_tauri/releases/tag/uvo-v1.0.0
