### ISSUE TITLE
Usability issues

### ISSUE THREAD

**Issue by GittingHubb** [delebash/unreal_vault_organizer#8]
Please add the option to **add tags to a selection of items** (now I have to add tags to each item one by one, this is very time consuming for medium-large collections)
Also please **ask for confirmation before deleting a tag** completely (especially if there are items that are using the tag).
I thought I had accidentally added a tag to the filter (because the **division between tag list and the filter** is unclear) so I accidentally deleted the tag altogether and had to (one by one) re-tag everything.

Also, please **allow changing tag colors** (makes things more clearer); And a **_NOT_ filter type**, to filter out a single (or multiple) tags.

Thank you for this tool, because otherwise Epic Games' vault is unusable.

**Comment by delebash** [comment]
Check out the new version that works with Fab and using tauri for smaller size.  I have also implemented your feature requests.  Check it out.  https://github.com/delebash/unreal_vault_organizer_tauri/releases/tag/uvo-v1.0.0
